server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: rental-processing-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      retries: 3
      acks: all

logging:
  level:
    org.springframework.kafka: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger
